- .circleci/config.yml
- .gitignore
- now.json
- package.json
- src/utils/NameMap.ts
- src/utils/asyncUtil.ts
- src/utils/valueUtil.ts
- tests/index.test.js
* Use `father` test
* Init CI
* Init test coverage
> chore: Add test case

- README.md
- examples/StateForm-context.tsx
- examples/components/LabelField.tsx
- src/Form.tsx
- src/FormContext.ts
- src/FormContext.tsx
- src/index.tsx
- src/useForm.ts
* Support global `validateMessages` config.
* Support communication between forms.
📸 [Context Demo](https://rc-field-form-git-context.react-component.now.sh/?selectedKind=rc-field-form&selectedStory=StateForm-context&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
📖 https://github.com/react-component/field-form/blob/context/README.md#formprovider
> feat: Support FormProvider

- .prettierrc
- README.md
- examples/StateForm-validate-perf.tsx
- examples/components/Input.tsx
- package.json
- src/interface.ts
- src/useForm.ts
- src/utils/validateUtil.ts
- tests/common/InfoField.tsx
- tests/common/index.js
- tests/common/timeout.ts
- tests/context.test.js
- tests/validate.test.js
* Customize validator support promise
* Warning if use `callback` or not return promise
* Add related test case
🐒 [StateForm-validate-perf](https://rc-field-form-git-promise.react-component.now.sh/?selectedKind=rc-field-form&selectedStory=StateForm-validate-perf&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fsource%2Fpanel)
> feat: Validator support promise

- README.md
- examples/StateForm-basic.tsx
- package.json
- src/Field.tsx
- src/useForm.ts
- tests/common/index.js
- tests/dependencies.test.js
Simplify render logic:
```jsx
<Form>
<Field name="field_1">
<input />
</Field>
<Field dependencies={['field_1']}>
{(_, _, { getFieldValue }) => (
getFieldValue('field_1') === 'aaa' &&
<Field name="field_1">
<input />
</Field>
)}
</Field>
</Form>
```
> feat: `dependencies` support trigger child Field update

- .eslintrc.js
- README.md
- src/Field.tsx
- src/FieldContext.ts
- src/interface.ts
- src/useForm.ts
- src/utils/asyncUtil.ts
- src/utils/validateUtil.ts
- tests/common/index.js
- tests/dependencies.test.js
- tests/legacy/async-validation.test.js
- tests/legacy/basic-form.test.js
- tests/legacy/clean-field.test.js
- tests/legacy/dom-form.test.js
- tests/legacy/dynamic-binding.test.js
Please help to check related document update about this: https://github.com/react-component/field-form/blob/f4c9c586d5a8ea4ed31f7934528b9800cbf0b8bf/README.md#different-with-rc-form
> chore: Add legacy test [part 1]

- README.md
- examples/StateForm-context.tsx
- src/FieldContext.ts
- src/Form.tsx
- src/FormContext.tsx
- src/interface.ts
- src/useForm.ts
- tests/context.test.js
```jsx
<FormProvider
onFormFinish={(name, { values, forms }) => {
if (name === 'form1') {
forms.form2.setFieldsValue({ ... });
}
}}
>
<Form name="form1">
<Field name="name" rules={[{ required: true }]}>
<Input />
</Field>
</Form>
<Form name="form2" />
</FormProvider>
```
> feat: Support `submit` & `onFormFinish`

- src/useForm.ts
- tests/validate.test.js
```jsx
<Form initialValues={{ user: 'light', pass: 'bamboo' }}>
<Field name="user" />
</Form>
```
Will only get `{ user: 'light' }` in `onFinish` or `validateFields`
> feat: Only provides values exist in the Fields

- src/useForm.ts
- tests/index.test.js
如果 hooks 注册后没有传入给 Form，调用其方法报 warning。
这似乎也解决了用户没注意直接干调的情况。
> warning if not regist form

- src/List.tsx
- tests/list.test.js
add `defaultValue` for `add` operation
#49
> feat: add defaultValue for add operation

- src/Field.tsx
- tests/index.test.js
以 `resetCount ` 作为 `key` 来限定 `returnChildNode` 渲染，`resetFields` 方法调用后，key 自增以重置 Field。
> fix: form.resetFields 会导致 field 子组件 mount 两次

- src/Field.tsx
I believe this should resolve the type error in the build output in `Field.d.ts`. The `Field` class implements the `FieldEntity` interface, but the generated type for the class differs from the interface resulting in this type error:
```
Property 'onStoreChange' in type 'Field' is not assignable to the same property in base type 'FieldEntity'.
Type '(prevStore: Store, namePathList: InternalNamePath[], info: NotifyInfo) => void' is not assignable to type '(store: Store, namePathList: InternalNamePath[] | null, info: NotifyInfo) => void'.
Types of parameters 'namePathList' and 'namePathList' are incompatible.
Type 'InternalNamePath[] | null' is not assignable to type 'InternalNamePath[]'.
Type 'null' is not assignable to type 'InternalNamePath[]'
```
I'm not entirely sure why the existing …
> Fix type error in Field.d.ts (fixes #67)

- .circleci/config.yml
- src/Form.tsx
- src/useForm.ts
- tests/validate.test.js
fix https://github.com/ant-design/ant-design/issues/21701
> fix onFinish get full value instead of filtered one

- examples/validate-perf.tsx
- src/Field.tsx
- src/utils/validateUtil.ts
- tests/validate.test.js
close #79
```
<Field
name="username"
messageVariables={{ label: '用户名' }}
rules={[{ required, message: '${label}是被需要的' }]}
/>
```
> feat: Field support `messageVariables`

- README.md
- src/Field.tsx
- tests/index.test.js
原本看和 `valuePropName` 比较雷同，就去掉了。现在看看（包括业务上的反馈）有一些特殊的用法还是需要的。
resolve https://github.com/ant-design/ant-design/issues/22896
resolve https://github.com/ant-design/ant-design/issues/19727
> feat: support getValueProps 

- src/useForm.ts
- tests/index.test.js
解决 `useEffect` 下调用 form 方法的 warning 问题。现在总是延迟检查。
```tsx
useEffect(() => {
if (visible) form.setFieldsValue({});
}, [visible]);
```
> chore: move warning delay

- src/Field.tsx
- tests/index.test.js
fix https://github.com/ant-design/ant-design/issues/23584
> fix: Should force re render when shouldUpdate is true

- src/Field.tsx
- src/utils/validateUtil.ts
- tests/validate.test.js
用户反馈很多次，准备默认改回按需调用。添加 `parallel` 属性用于有提速需求的用户。
ref https://github.com/ant-design/ant-design/issues/21793
> feat: add Parallel

- src/List.tsx
- tests/list.test.js
fix a crash like:
`form.setFieldsValue({ list: null })`
> fix: List should not crash when it's not a array value

- src/List.tsx
- tests/list.test.js
ref issue：https://github.com/ant-design/ant-design/issues/26012
> feat: add() support index param

- examples/list.tsx
- src/Field.tsx
- src/useForm.ts
- tests/preserve.test.tsx
resolve https://github.com/ant-design/ant-design/issues/26184
> fix: Preserve should not affect Form.List

- examples/list.tsx
- src/List.tsx
- src/interface.ts
- src/utils/validateUtil.ts
- tests/list.test.js
ref https://github.com/ant-design/ant-design/issues/25717
close #168
> feat: Form.List support `rules`

- src/Field.tsx
- tests/validate.test.js
fix https://github.com/ant-design/ant-design/issues/27059
> fix: submit not trigger field re-render

- src/useForm.ts
- tests/preserve.test.tsx
resolve https://github.com/ant-design/ant-design/issues/27581
> fix: Nest Field will trigger clean all store when `preserve=false`

- src/Field.tsx
- src/List.tsx
- src/index.tsx
- src/interface.ts
- src/useForm.ts
- tests/list.test.tsx
resolve https://github.com/ant-design/ant-design/issues/27576
> fix: Nest Field.List item will not clean up on `onValuesChange` when removed

- .eslintrc.js
- .prettierrc
- examples/list.tsx
- package.json
- src/Field.tsx
- src/List.tsx
- src/interface.ts
- src/useForm.ts
- tests/list.test.tsx
英文说不清，举例说明。
如果有 2 个字段 `user.name` 和 `user.age`：
* 修改其中之一时
* `isFieldsTouched(['user'], false)` 返回 `true`，因为任意子节点变化都作为虚拟父字段变化
* `isFieldsTouched(['user'], true)` 返回 `false`，因为尚有子节点没有变化，传导给虚拟父节点也没有变化
如果是一个 `List(name="user")`，包含两个槽位 `[a, b]`：
* 修改其中之一时
* 【同上】`isFieldsTouched(['user'], false)` 返回 `true`，因为任意子节点变化都作为虚拟父字段变化
* 【同上】`isFieldsTouched(['user'], true)` 返回 `false`，因为尚有子节点没有变化，传导给虚拟父节点也没有变化
* 增减数量时
* `isFieldsTouched(['user'], false)` 返回 `true`，因为 List 字段本身变化了
* `isFieldsTouched(['user'], true)` 返回 `false`，因为尚有子节点没有变化
`isFieldTouched` 内部实现始终为 `isFieldsTouched([namePath], false)`。
> feat: Summary touched status

- src/Field.tsx
- src/interface.ts
- src/useForm.ts
- tests/common/InfoField.tsx
- tests/common/index.ts
- tests/dependencies.test.js
- tests/legacy/dynamic-binding.test.js
- tests/validate.test.tsx
`dependencies` 的字段在 renderProps 的 Field 下延迟一个 Promise 以确保 `rules` 保持同步更新。
> fix: RenderProps deps validate

- package.json
NPM 7 automatically installs peer dependencies. Trying to update to React 17 causes error when installing @ant-design/icons
More info here: https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
Based on the advice from Kent C. Dodds and Cory House, I updated peer dependency of React to be ">= 16.9.0"
Tweets: https://mobile.twitter.com/kentcdodds/status/1325565636303482880
> Fix issue with NPM 7 throwing error

- .gitignore
- .umirc.ts
- now.json
https://field-form.react-component.now.sh/demo/basic
链接为具体 demo 时，会 404 
进 https://field-form.react-component.now.sh/  主页，选 Demo 不会
> chore: fix route html

- .eslintrc.js
- src/useForm.ts
- src/utils/NameMap.ts
Move array to map. It's a little hack but valuable.
> refactor: Enhance cache util perf

- package.json
- src/Field.tsx
- src/useForm.ts
- src/utils/valueUtil.ts
- tests/preserve.test.tsx
ref https://github.com/ant-design/ant-design/issues/29215
嵌套子字段可以通过 `preserve={false}` 在移除时删掉对应字段，需要发个 minor。
> feat: Form.List nest Field.Item support `preserve={false}`

- src/Form.tsx
- tests/index.test.js
fix #https://github.com/ant-design/ant-design/issues/29439
Besides, put the ...restProps behind, so that user can cover it
> feature: add default onReset props on Form component

- docs/examples/components/LabelField.tsx
- docs/examples/validate-perf.tsx
- docs/examples/validate.tsx
- package.json
- src/Field.tsx
- src/FieldContext.ts
- src/interface.ts
- src/useForm.ts
- src/utils/asyncUtil.ts
- src/utils/validateUtil.ts
- tests/common/InfoField.tsx
- tests/common/index.ts
- tests/context.test.js
- tests/index.test.js
- tests/validate-warning.test.tsx
- tests/validate.test.tsx
本来以为要改 `async-validator`，好像勾一下也行了？
顺道做了一下：https://github.com/ant-design/ant-design/issues/30016
> feat: rules support `warningOnly`

- docs/examples/validate-perf.tsx
- package.json
- src/Field.tsx
- src/FieldContext.ts
- src/interface.ts
- src/useForm.ts
- tests/dependencies.test.js
resolve https://github.com/ant-design/ant-design/issues/30995
> fix: `initialValue` should trade as validate condition

- .gitignore
- docs/demo/initialValues.md
- docs/examples/initialValues.tsx
- docs/examples/useForm.tsx
- src/useForm.ts
- src/utils/cloneDeep.ts
- src/utils/valueUtil.ts
- tests/index.test.js
- tests/initialValue.test.js
- tests/utils.test.js
- Revert "revert: revert initialValues protect (#376)"
- fix: deep clone array for initialValues
> fix: deep clone array for initialValues

- docs/examples/useWatch.tsx
- src/interface.ts
- src/useForm.ts
- src/useWatch.ts
- src/utils/typeUtil.ts
- tests/useWatch.test.tsx
The existing prop `preserve` in `Form` is used to keep values even if the field is not rendered. However, it will not trigger the `watchList` because the `getFieldsValue` is called without `true` and will return only the visible fields.
`Form` 目前已有的 `preserve` 属性是用来在 field 没有被渲染的情况下依旧能获取值。但它不能触发 `watchList`，因为内部的 `getFieldsValue` 在不传 `true` 的情况下只会返回可见的 fields。
> feat(useWatch): notify watch in preserve mode

- src/List.tsx
- tests/preserve.test.tsx
Form.List 直接嵌套时由于 Form.List 自身不支持 `isListField` 属性导致删除时会错误还原，补上即可：
fix https://github.com/ant-design/ant-design/issues/41740
> fix: Form.List nested not support `preserve=false`

- src/Field.tsx
- tests/validate.test.tsx
- close https://github.com/ant-design/ant-design/issues/41966
之前我们是根据 validatePromise 是否为 null 来判断是否触发过校验的，但我们之前漏了重置的时候，把 validatePromise 设置为 undefined 了，导致重置后依然是 null, 所以导致点击重置之后校验的状态一直还保留着。
> fix: validated should be reset when trigger reset event

- src/Field.tsx
- src/List.tsx
- src/ListContext.ts
- tests/list.test.tsx
close https://github.com/ant-design/ant-design/issues/41053
> fix: form onValues second params values

- docs/demo/validateOnly.md
- docs/examples/validateOnly.tsx
- src/Field.tsx
- src/interface.ts
- src/useForm.ts
- src/utils/validateUtil.ts
- tests/validate.test.tsx
Call `form.validateFields({ validateOnly: true })` will not trigger UI state update but only validate silent.
> feat: Support `validateOnly`

- src/interface.ts
- fix: https://github.com/ant-design/ant-design/issues/42941
Before:
After:
> fix: optimize type definition

- docs/examples/basic.tsx
- src/interface.ts
- src/useForm.ts
- tests/validate.test.tsx
ref https://github.com/ant-design/ant-design/issues/43276
> fix: should not trigger `onFieldsChange` when `submit`

- src/interface.ts
fix https://github.com/ant-design/ant-design/issues/43305
before:
after:
> fix: setFieldsValue bug with union type of Array and null

- src/Field.tsx
- tests/index.test.tsx
收到 observer 通知时会触发一次 metaChange，但是对于不影响的 Field 不应该去触发。
fix https://github.com/ant-design/ant-design/issues/43557
> fix: onMetaChange trigger when meta not changed

- .github/workflows/main.yml
- .gitignore
- src/useWatch.ts
- tests/useWatch.test.tsx
ref https://github.com/facebook/react/issues/27213
> Fix use watch trigger re-render twice in React 18

- src/Field.tsx
- src/useForm.ts
- tests/index.test.tsx
- tests/initialValue.test.tsx
ref #45010
修复底层 `setFields` 不会触发子路径匹配更新的问题。
> fix: `setField` or `setFields` or `setFieldValue` should update field

- src/interface.ts
- src/useForm.ts
- tests/common/timeout.ts
- tests/validate.test.tsx
ref https://github.com/ant-design/ant-design/issues/42347
> feat: validate support dirty

- docs/demo/useWatch-selector.md
- docs/examples/useWatch-selector.tsx
- src/useWatch.ts
- tests/useWatch.test.tsx
RFC: https://github.com/ant-design/ant-design/discussions/46173
> feat: useWatch support selector

- src/Field.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
关联 PR https://github.com/ant-design/ant-design/pull/46445
关联 issue https://github.com/ant-design/ant-design/issues/46417
根据 #46445  的改动为 getValueProps 的返回值加上一层 warning，判断返回值是否为 function 是 function 则给予提示
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Add a prompt for the error message returned by the Field component's getValueProps      |
| 🇨🇳 Chinese |     为  Field 组件的 getValueProps  返回错误提示增加提示  |
⚠️ Please check all items below before requesting a reviewing. ⚠️
> feat: add warning "cannot be a function" in getValueProps

- src/Field.tsx
- tests/index.test.tsx
> fix: setFieldsValue should tread same as setField

- package.json
- src/Field.tsx
修复 `process.env.NODE_ENV` 不存在的 bug
> type: fix process.env.NODE_ENV is undefined

- src/Field.tsx
- tests/index.test.tsx
ref: [ant-design/ant-design#47952](https://github.com/ant-design/ant-design/issues/47952)
> fix: `getValueProps` should not be executed when `name` does not exist

- src/Field.tsx
- tests/validate.test.tsx
defaultProps 已废弃：
- https://github.com/facebook/react/pull/16210
> chore: clear any

- src/Form.tsx
- src/index.tsx
- src/interface.ts
- tests/index.test.tsx
close https://github.com/ant-design/ant-design/issues/48776
Form 组件 ref 增加原生 Dom 节点
> feat: ref adding nativeElement

- src/utils/validateUtil.ts
- tests/validate.test.tsx
Modify the `replaceMessage` function in `src/utils/validateUtil.ts` to handle escaped variables and add related test cases.
* **replaceMessage function**:
- Update the `replaceMessage` function to skip conversion when `\${xxx}` is passed and convert `${xxx}` correctly.
- Check for the presence of `\${xxx}` and skip conversion in such cases.
- Ensure the function correctly converts `${xxx}` to the corresponding value from the `kv` object.
* **validate.test.tsx**:
- Add test cases to verify the correct handling of `\${xxx}` and `${xxx}`.
- Ensure the test cases cover both scenarios: skipping conversion and converting correctly.
- Add a new test case to handle escaped and unescaped variables correctly.
---
For more details, open the [Copilot Workspace …
> Fix replaceMessage function to handle escaped variables

- src/Field.tsx
Introduce a new constant `EMPTY_WARNINGS` for use with `warnings` to avoid both `errors` and `warnings` pointing to the same array reference.
新增一個 `EMPTY_WARNINGS` 給 `warnings` 使用，以避免 `errors` 與 `warnings` 指向同一個 array reference。
fix #649
> fix: assign distinct initial values to both `errors` and `warnings` to prevent `isEqual` from encountering circular references
