react-component/field-form

.eslintrc.js
.gitignore
README.md
package.json
src/Field.tsx
src/FieldContext.ts
src/List.tsx
src/index.tsx
src/interface.ts
src/useForm.ts
src/utils/validateUtil.ts

ReadMe: https://github.com/react-component/field-form/blob/docs/README.md#api
Preview: https://rc-field-form-git-docs.react-component.now.sh/

docs: Add readme document

---

README.md
package.json
src/Form.tsx
src/utils/validateUtil.ts
tests/index.test.js

feat: Support `component` on Form

---

README.md
examples/validate-perf.tsx
src/Form.tsx
src/interface.ts
src/useForm.ts
tests/index.test.js

```jsx
<Form onFinish={onFinish} onFinishFailed={onFinishFailed}>
<Field name="test" rules={[{ required: true }]}>
<Input />
</Field>
<Button type="submit">Submit</Button>
</Form>
```
cc @JIACHENG9

feat: support onFinishFailed

---

src/interface.ts

@zombieJ typescript 项目 使用自定义验证，rule 定义错了

fix: Update validator typescript definition

---

src/utils/validateUtil.ts
tests/validate.test.js

ref: ant-design/ant-design#17954

feat: Console error additional info

---

src/interface.ts

[#60](https://github.com/react-component/field-form/issues/60)

fix: type definition error of property ValidateErrorEntity.errorFields

---

package.json
src/Field.tsx
tests/index.test.js

fix https://github.com/ant-design/ant-design/issues/21065

fix: `shouldUpdate` should also work on `setFields`

---

src/Field.tsx
src/utils/validateUtil.ts
tests/validate.test.js

close https://github.com/ant-design/ant-design/issues/21145

feat: Field support `validateFirst`

---

src/interface.ts
src/useForm.ts
tests/index.test.js

Had some time today to play with it a bit, so here is a PR, hope it can be useful.
I did it in the most straightforward way looking at existing code.
But maybe you have another API in mind.

feat: add form.getFieldsValue filterFunc (closes #43)

---

src/utils/validateUtil.ts
tests/validate.test.js

ref https://github.com/ant-design/ant-design/issues/21305

fix validateFirst

---

examples/basic.tsx
examples/validate.tsx
src/Field.tsx
src/Form.tsx
src/interface.ts
src/useForm.ts

ref https://github.com/ant-design/ant-design/pull/21323
Note: This update will reduce render props perf.

refactor: getFieldValues default only get registered field

---

examples/basic.tsx
examples/validate.tsx
src/Field.tsx
src/Form.tsx
src/interface.ts
src/useForm.ts

Reverts react-component/field-form#77
ref https://github.com/ant-design/ant-design/issues/21435#issuecomment-588010891

Revert "refactor: getFieldValues default only get registered field"

---

README.md
src/Field.tsx
src/interface.ts
src/useForm.ts
tests/index.test.js

Close https://github.com/ant-design/ant-design/issues/21816

feat: Add Field[initialValue]

---

.gitignore
src/Field.tsx
tests/validate.test.js

fix https://github.com/ant-design/ant-design/issues/22400

fix: Change name should rest field

---

examples/redux.tsx
src/Field.tsx
src/interface.ts
src/useForm.ts
tests/control.test.js

fix https://github.com/ant-design/ant-design/issues/21922

fix: control `fields` should correct handle error messages

---

src/Field.tsx

ant-design/ant-design/issues/22923

Form typescript shouldUpdate type

---

package.json
src/Field.tsx
src/interface.ts
src/useForm.ts
tests/dependencies.test.js

resolve https://github.com/ant-design/ant-design/issues/23715

fix: dependencies should work when field is already validated

---

src/Field.tsx
src/Form.tsx
src/interface.ts
tests/validate.test.js

ref https://github.com/ant-design/ant-design/issues/23748

feat: Form support `validateTrigger`

---

src/Field.tsx
src/List.tsx
tests/list.test.js

ref https://github.com/ant-design/ant-design/issues/23978

fix: List.Field should keep status

---

src/Field.tsx
src/interface.ts
src/useForm.ts
src/utils/NameMap.ts

resolve https://github.com/ant-design/ant-design/issues/24558

chore: Opt of form store

---

src/useForm.ts

https://github.com/react-component/field-form/commit/a7e3373#r39550472
https://github.com/ant-design/ant-design/pull/24604#issuecomment-636348597
https://github.com/ant-design/ant-design/pull/24601#issuecomment-636341004

fix SSR render

---

README.md
src/Field.tsx
src/FieldContext.ts
src/Form.tsx
src/interface.ts
src/useForm.ts
tests/common/InfoField.tsx
tests/perishable.test.tsx
tests/preserve.test.tsx

ref https://github.com/ant-design/ant-design/issues/24729

feat: support perishable

---

examples/deps.tsx
src/Field.tsx
tests/dependencies.test.js

resolve https://github.com/ant-design/ant-design/issues/21645

feat: use `deps` as a shortcut of `shouldUpdate` when name is not set

---

src/useForm.ts
tests/list.test.js

fix https://github.com/ant-design/ant-design/issues/25584

fix: Preserve should not break Form.List

---

src/List.tsx
tests/list.test.js

The pr of ASOC to solve this feature：https://github.com/ant-design/ant-design/issues/22298
给 Form.LIst 组件提供一个数组的类型来支持批量删除的功能。

feat: remove in Form.list support array

---

examples/basic.tsx
examples/useForm.tsx
src/Form.tsx
src/index.tsx
src/interface.ts
src/useForm.ts

resolve https://github.com/react-component/field-form/issues/70

feat: Form & FormInstance support generic

---

src/utils/validateUtil.ts
tests/validate.test.js

resolve https://github.com/ant-design/ant-design/issues/25971

fix: validateFirst should not always pass

---

src/useForm.ts
tests/index.test.js

resolve https://github.com/ant-design/ant-design/issues/26801

fix: onValuesChange should not return store

---

.eslintignore
.github/workflows/main.yml
.gitignore
.vscode/settings.json
package.json

清理了一下，使用 father 的配置。
@PeachScript README.md 还需要搞一搞~

docs: More actions on dumi

---

docs/examples/list.tsx
src/List.tsx
tests/list.test.tsx

ref https://github.com/ant-design/ant-design/issues/27763

feat: List support initialValues

---

src/Field.tsx

Fix ant-design/ant-design#27534 and ant-design/ant-design#27888

Declare property fieldContext as optional

---

src/Field.tsx
src/FieldContext.ts
src/interface.ts
src/useForm.ts
tests/strict.test.tsx

resolve https://github.com/ant-design/ant-design/issues/27842

fix: onFieldsChange in strict mode

---

src/utils/validateUtil.ts
tests/validate.test.tsx

fix: Async validator type check

---

docs/examples/basic.tsx
src/Field.tsx
src/interface.ts
src/useForm.ts
src/utils/valueUtil.ts
tests/preserve.test.tsx

follow up #329
resolve https://github.com/ant-design/ant-design/issues/31297
close #329

fix: shouldUpdate should trigger on field removed

---

src/Field.tsx
src/FormContext.tsx
src/index.tsx
src/interface.ts
src/utils/valueUtil.ts
tests/index.test.js

close https://github.com/ant-design/ant-design/issues/33380

fix: cannot use 'in' operator to search for "value"

---

package.json

close https://github.com/react-component/field-form/issues/344

fix: peerDependencies typo

---

.gitignore
docs/demo/initialValues.md
docs/examples/initialValues.tsx
src/useForm.ts
src/utils/cloneDeep.ts
src/utils/valueUtil.ts
tests/initialValue.test.js
tests/utils.test.js

close https://github.com/ant-design/ant-design/issues/33981

fix: initValues should not be modified if preserve is false

---

src/FieldContext.ts
src/Form.tsx
src/interface.ts
src/useForm.ts
tests/index.test.js
tests/initialValue.test.js

resolve https://github.com/ant-design/ant-design/issues/34768
ref https://github.com/ant-design/ant-design/issues/33981

fix: Remount form should keep origin store value

---

docs/examples/useWatch-list.tsx
src/useWatch.ts
tests/useWatch.test.tsx

Fiber 在时间充裕的时候会跳过 compare 阶段，使用 ref 跳过没有必要的渲染。

fix: No more render times

---

package.json
src/utils/validateUtil.ts

fix: async-validator compitable

---

src/useWatch.ts
tests/useWatch.test.tsx

resolve https://github.com/react-component/field-form/issues/431

fix: useWatch object trigger re-render

---

jest.config.js
package.json
src/FieldContext.ts
src/interface.ts
src/useForm.ts
tests/index.test.js
tests/setupAfterEnv.ts

https://github.com/ant-design/ant-design/issues/34863

feat: Add `setFieldValue` API

---

docs/examples/validate.tsx
package.json
src/Field.tsx
src/index.tsx
src/useForm.ts
tests/legacy/validate-array.test.js

close https://github.com/ant-design/ant-design/issues/36436

fix: TypeError ruleErrors.forEach on rule type: 'array' with defaultField

---

src/Field.tsx
tests/validate.test.tsx

fix https://github.com/ant-design/ant-design/issues/38201

fix: invalidate rule should not failed

---

src/useForm.ts
tests/validate.test.tsx

@kiner-tang  加了 `validated` 正好这边也加个测试，所以 antd 那边要 minor 版本才会好~
resolve https://github.com/ant-design/ant-design/issues/41051

fix: onFieldsChange not trigger when validating

---

src/utils/validateUtil.ts
src/utils/valueUtil.ts
tests/validate.test.tsx

**背景**
close: https://github.com/ant-design/ant-design/issues/40497
**实现**
自定义 warning 方法，直接不输出 warning

chore: disable validate waring log

---

src/Form.tsx
tests/list.test.tsx

fix https://github.com/ant-design/ant-design/issues/43005

fix: ListContext makes nest Form event bubble out of range

---

src/useWatch.ts

https://github.com/ant-design/ant-design/pull/42750
- (undefined) Circular dependency detected:
node_modules/rc-field-form/es/index.js -> node_modules/rc-field-form/es/useWatch.js -> node_modules/rc-field-form/es/index.js @kiner-tang
- (undefined) Circular dependency detected:
node_modules/rc-field-form/es/useWatch.js -> node_modules/rc-field-form/es/index.js -> node_modules/rc-field-form/es/useWatch.js @kiner-tang

refactor: solve field-form circular dependency issue

---

src/index.tsx
src/interface.ts
src/useForm.ts
tests/list.test.tsx

添加 Form.STRICT 会同时过滤掉 Form.List 中的数据。
```tsx
form.getFieldsValue(Form.STRICT);
```
ref https://github.com/ant-design/ant-design/issues/43300

feat: support Form.STRICT

---

src/namePathType.ts
tests/nameTypeCheck.test.tsx

fix: https://github.com/ant-design/ant-design/issues/44001

fix: type is unknown

---

src/interface.ts
src/useForm.ts
src/utils/valueUtil.ts
tests/validate.test.tsx

`validateFields` 支持递归校验
ref https://github.com/ant-design/ant-design/issues/44089

feat: support `recursive` validation

---

src/Field.tsx
tests/validate.test.tsx

月经需求。之前也是让开发者自己去搞，但是的确也是不方便还很容易写错。内置了。
ref https://github.com/ant-design/ant-design/issues/44585

feat: Field support `validateDebounce`

---

src/useForm.ts
tests/initialValue.test.tsx

ref https://github.com/ant-design/ant-design/issues/44861

fix: Reset should ignore ListField

---

docs/demo/fieldTouched.md
docs/examples/fieldTouched.tsx
src/useForm.ts
tests/list.test.tsx

修复`form.isFieldsTouched(true)`在`Form.List`场景下返回错误的问题
https://github.com/react-component/field-form/issues/652

fix: isFieldsTouched return wrong result with param true

---

.github/dependabot.yml
.github/workflows/main.yml

https://github.com/react-component/field-form/actions/runs/8889925235/job/24409068246?pr=685

chore: upgrade workflows

---

tests/common/index.ts
tests/list.test.tsx
tests/useWatch.test.tsx
tests/validate.test.tsx

test: rm legacy react-dom/test-utils

test: rm legacy react-dom/test-utils

---

src/namePathType.ts

ref: https://github.com/ant-design/ant-design/issues/49185

feat: DeepNamePath deep = 5

---

src/Field.tsx
tests/dependencies.test.tsx

ref https://github.com/ant-design/ant-design/issues/50283

fix: preserve false should not trigger shouldUpdate rerender
